### ISSUE TITLE
Publishing the Package

### ISSUE THREAD

**Issue by giovannilattanzio** [mitchhymel/dart-igdb_client#1]
Does a publishing of this library is on the way?

It would be great to have it on [https://pub.dartlang.org/](url) and be able to install it from pubspec

**Comment by mitchhymel** [comment]
The main reasons I haven't published this as a package yet are:
1) There's no error handling
2) I haven't 100% finalized the APIs

I do plan to finish this at some point, but can't promise this anytime soon.

If you want to use the library now, you can just clone the repo and reference it in your pubspec via path.

**Comment by mitchhymel** [comment]
@giovannilattanzio  I did end up adding some error handling and logging. I feel comfortable with how the client API surface looks, so I decided to publish as a package: https://pub.dartlang.org/packages/igdb_client

I also noticed there was another dart igdb library (https://pub.dartlang.org/packages/igdb_wrapper) published by someone else - that might be worth checking out.
